# Generated by Django 4.2.18 on 2026-01-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frontend", "0007_installation_consommation_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatterySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacite_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Capacité totale (kWh)",
                        max_digits=6,
                    ),
                ),
                (
                    "capacite_utilisable_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Capacité utilisable = capacite × 0.9",
                        max_digits=6,
                    ),
                ),
                (
                    "puissance_max_kw",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Puissance max charge/décharge (kW)",
                        max_digits=6,
                    ),
                ),
                (
                    "efficacite",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.95,
                        help_text="Rendement charge/décharge (0.90-0.98)",
                        max_digits=4,
                    ),
                ),
                (
                    "cycles_garantis",
                    models.IntegerField(
                        default=6000, help_text="Cycles garantis (6000 typique)"
                    ),
                ),
                (
                    "dod_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        help_text="Depth of Discharge max (0.90)",
                        max_digits=4,
                    ),
                ),
                (
                    "cycles_annuels",
                    models.IntegerField(
                        blank=True, help_text="Cycles/an calculés", null=True
                    ),
                ),
                (
                    "duree_vie_annees",
                    models.IntegerField(
                        blank=True, help_text="Durée de vie estimée", null=True
                    ),
                ),
                (
                    "autoconso_gain_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gain autoconso (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cout_installation",
                    models.DecimalField(
                        decimal_places=2, help_text="Coût batterie (€)", max_digits=10
                    ),
                ),
                (
                    "economie_annuelle",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Économies annuelles (€)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "roi_annees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ROI (années)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery",
                        to="frontend.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batterie",
                "verbose_name_plural": "Batteries",
                "db_table": "battery_systems",
            },
        ),
        migrations.CreateModel(
            name="BatteryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.IntegerField(help_text="Heure (0-8759)")),
                ("soc_kwh", models.DecimalField(decimal_places=3, max_digits=6)),
                ("soc_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("charge_kwh", models.DecimalField(decimal_places=3, max_digits=6)),
                ("discharge_kwh", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="battery.batterysystem",
                    ),
                ),
            ],
            options={
                "db_table": "battery_logs",
                "indexes": [
                    models.Index(
                        fields=["battery", "hour"],
                        name="battery_log_battery_8c32fb_idx",
                    )
                ],
            },
        ),
    ]
