# Generated by Django 4.2.18 on 2026-01-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_calc", "0004_alter_consumptionprofilemodel_id_and_more"),
        ("battery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batterysystem",
            name="simulation",
        ),
        migrations.AddField(
            model_name="batterysystem",
            name="installation",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battery",
                to="solar_calc.solarinstallationmodel",
            ),
            preserve_default=False,
        ),
    ]
