# Generated by Django 4.2.18 on 2026-01-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("puissance_kw", models.FloatField(help_text="Puissance en kWc")),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("N", "Nord"),
                            ("NE", "Nord-Est"),
                            ("E", "Est"),
                            ("SE", "Sud-Est"),
                            ("S", "Sud"),
                            ("SW", "Sud-Ouest"),
                            ("W", "Ouest"),
                            ("NW", "Nord-Ouest"),
                        ],
                        max_length=2,
                    ),
                ),
                ("inclinaison", models.IntegerField(help_text="Angle en degrés")),
                (
                    "type_toiture",
                    models.CharField(
                        choices=[
                            ("tuiles", "Tuiles"),
                            ("ardoise", "Ardoise"),
                            ("zinc", "Zinc"),
                            ("beton", "Béton"),
                            ("tole", "Tôle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontend_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resultat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("production_annuelle_kwh", models.FloatField(help_text="kWh/an")),
                (
                    "production_mensuelle_kwh",
                    models.JSONField(help_text="Données mensuelles"),
                ),
                (
                    "production_horaire_kwh",
                    models.JSONField(help_text="Profil horaire moyen"),
                ),
                ("consommation_annuelle_kwh", models.FloatField(help_text="kWh/an")),
                ("consommation_mensuelle_kwh", models.JSONField()),
                ("consommation_horaire_kwh", models.JSONField()),
                ("autoconsommation_ratio", models.FloatField(help_text="En %")),
                (
                    "injection_reseau_kwh",
                    models.FloatField(help_text="kWh injectés annuellement"),
                ),
                ("economie_annuelle_euros", models.FloatField(default=0)),
                ("roi_25ans_euros", models.FloatField(default=0)),
                ("taux_rentabilite_pct", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ En attente"),
                            ("running", "🔄 En cours"),
                            ("success", "✅ Terminée"),
                            ("failed", "❌ Erreur"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="ID de la tâche Celery", max_length=255
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="frontend.installation",
                    ),
                ),
                (
                    "resultat",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation",
                        to="frontend.resultat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
