# Generated by Django 4.2.18 on 2026-01-12 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppareilElectrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "puissance_nominale_w",
                    models.IntegerField(help_text="Puissance nominale en Watts"),
                ),
                (
                    "puissance_veille_w",
                    models.IntegerField(default=0, help_text="Puissance en veille (W)"),
                ),
                (
                    "heures_jour_defaut",
                    models.FloatField(
                        default=1.0,
                        help_text="Heures d'utilisation par jour (moyenne)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "jours_semaine_defaut",
                    models.IntegerField(
                        default=7,
                        help_text="Jours d'utilisation par semaine",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "variations_mensuelles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Facteurs multiplicateurs par mois (1-12)",
                    ),
                ),
                (
                    "consommation_annuelle_kwh",
                    models.FloatField(
                        editable=False,
                        help_text="Consommation annuelle calculée automatiquement",
                    ),
                ),
                (
                    "questions_personnalisees",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Questions spécifiques pour cet appareil",
                    ),
                ),
                (
                    "formule_calcul",
                    models.TextField(
                        blank=True,
                        help_text="Formule Python pour calcul personnalisé (optionnel)",
                    ),
                ),
                (
                    "mode_rapide",
                    models.BooleanField(
                        default=True, help_text="Apparaît dans le mode rapide"
                    ),
                ),
                (
                    "mode_expert",
                    models.BooleanField(
                        default=True, help_text="Apparaît dans le mode expert"
                    ),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Appareil électrique",
                "verbose_name_plural": "Appareils électriques",
                "ordering": ["category__ordre", "ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="AppareillectriqueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "ordre",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="⚡", help_text="Emoji ou icône", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pourcentage_moyen",
                    models.FloatField(
                        default=10.0,
                        help_text="% moyen de la consommation totale",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'appareil",
                "verbose_name_plural": "Catégories d'appareils",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ConsommationCalculee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surface_habitable",
                    models.FloatField(
                        help_text="Surface habitable en m²",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "nb_personnes",
                    models.IntegerField(
                        help_text="Nombre de personnes dans le foyer",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                (
                    "dpe",
                    models.CharField(
                        choices=[
                            ("A", "A - Très performant (< 50 kWh/m²/an)"),
                            ("B", "B - Performant (50-90 kWh/m²/an)"),
                            ("C", "C - Assez performant (91-150 kWh/m²/an)"),
                            ("D", "D - Moyen (151-230 kWh/m²/an)"),
                            ("E", "E - Médiocre (231-330 kWh/m²/an)"),
                            ("F", "F - Énergivore (331-450 kWh/m²/an)"),
                            ("G", "G - Très énergivore (> 450 kWh/m²/an)"),
                        ],
                        help_text="Étiquette DPE du logement",
                        max_length=1,
                    ),
                ),
                (
                    "annee_construction",
                    models.IntegerField(
                        blank=True,
                        help_text="Année de construction du logement",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "type_chauffage",
                    models.CharField(
                        choices=[
                            ("electrique", "Électrique (convecteurs, radiateurs)"),
                            ("pac", "Pompe à chaleur (PAC)"),
                            ("gaz", "Gaz"),
                            ("fioul", "Fioul"),
                            ("bois", "Bois / Granulés"),
                            ("autre", "Autre"),
                        ],
                        default="electrique",
                        max_length=50,
                    ),
                ),
                (
                    "temperature_consigne",
                    models.FloatField(
                        default=19.0,
                        help_text="Température de chauffage souhaitée (°C)",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "type_vmc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple_flux", "VMC Simple flux"),
                            ("double_flux", "VMC Double flux"),
                            ("naturelle", "Ventilation naturelle"),
                            ("aucune", "Aucune / Je ne sais pas"),
                        ],
                        default="aucune",
                        max_length=50,
                    ),
                ),
                (
                    "type_ecs",
                    models.CharField(
                        choices=[
                            ("ballon_electrique", "Ballon électrique (cumulus)"),
                            ("thermodynamique", "Chauffe-eau thermodynamique"),
                            ("gaz", "Chauffe-eau gaz"),
                            ("solaire", "Chauffe-eau solaire"),
                            ("autre", "Autre"),
                        ],
                        default="ballon_electrique",
                        max_length=50,
                    ),
                ),
                (
                    "capacite_ecs_litres",
                    models.IntegerField(
                        blank=True,
                        help_text="Capacité du ballon d'eau chaude (litres)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "zone_climatique",
                    models.CharField(
                        choices=[
                            ("H1", "H1 - Nord"),
                            ("H2", "H2 - Centre"),
                            ("H3", "H3 - Sud"),
                        ],
                        default="H2",
                        max_length=2,
                    ),
                ),
                (
                    "mode_calcul",
                    models.CharField(
                        choices=[("rapide", "Mode Rapide"), ("expert", "Mode Expert")],
                        default="rapide",
                        max_length=20,
                    ),
                ),
                (
                    "consommation_annuelle_totale",
                    models.FloatField(
                        help_text="Consommation totale calculée (kWh/an)"
                    ),
                ),
                (
                    "consommation_moyenne_attendue",
                    models.FloatField(
                        help_text="Consommation moyenne pour ce profil (kWh/an)"
                    ),
                ),
                (
                    "ecart_pourcentage",
                    models.FloatField(help_text="Écart par rapport à la moyenne (%)"),
                ),
                (
                    "repartition_postes",
                    models.JSONField(
                        default=dict,
                        help_text="Répartition de la consommation par poste",
                    ),
                ),
                (
                    "consommation_mensuelle",
                    models.JSONField(
                        default=list, help_text="Consommation mensuelle (12 valeurs)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommation_calculee",
                        to="frontend.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consommation calculée",
                "verbose_name_plural": "Consommations calculées",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppareilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        default=1,
                        help_text="Nombre d'appareils de ce type",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "heures_jour",
                    models.FloatField(
                        blank=True,
                        help_text="Heures d'utilisation par jour (override)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "jours_semaine",
                    models.IntegerField(
                        default=7,
                        help_text="Jours d'utilisation par semaine",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "mois_utilisation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Mois d'utilisation (1-12). Vide = toute l'année",
                    ),
                ),
                (
                    "parametres_personnalises",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Réponses aux questions spécifiques",
                    ),
                ),
                (
                    "consommation_annuelle_kwh",
                    models.FloatField(
                        help_text="Consommation annuelle de cet appareil (kWh/an)"
                    ),
                ),
                (
                    "consommation_mensuelle",
                    models.JSONField(
                        default=list, help_text="Consommation mensuelle (12 valeurs)"
                    ),
                ),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisations",
                        to="frontend.appareilelectrique",
                    ),
                ),
                (
                    "consommation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appareils_utilisateur",
                        to="frontend.consommationcalculee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil utilisateur",
                "verbose_name_plural": "Appareils utilisateur",
                "ordering": ["appareil__category__ordre", "appareil__ordre"],
            },
        ),
        migrations.AddField(
            model_name="appareilelectrique",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appareils",
                to="frontend.appareillectriquecategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appareilelectrique",
            unique_together={("category", "slug")},
        ),
    ]
