# Generated by Django 4.2.18 on 2026-01-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_appareilelectrique_appareillectriquecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consommationcalculee",
            name="details_financiers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
