# Generated by Django 4.2.18 on 2026-01-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_consommationcalculee_details_financiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consommationcalculee",
            name="details_financiers",
        ),
    ]
