# Generated by Django 4.2.18 on 2026-01-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_remove_details_financiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="consommationcalculee",
            name="economie_optimisation_hphc",
            field=models.FloatField(
                blank=True,
                help_text="Économie annuelle possible en € avec optimisation HP/HC",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="heure_coucher",
            field=models.IntegerField(
                blank=True, help_text="Heure de coucher (0-23)", null=True
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="heure_lever",
            field=models.IntegerField(
                blank=True, help_text="Heure de lever (0-23)", null=True
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="pct_hc_actuel",
            field=models.FloatField(
                blank=True,
                help_text="% actuel de consommation en heures creuses",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="pct_hc_optimal",
            field=models.FloatField(
                blank=True, help_text="% optimal possible avec programmation", null=True
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="profil_usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("actif_absent", "Actif absent (travail)"),
                    ("teletravail_partiel", "Télétravail partiel"),
                    ("teletravail_complet", "Télétravail complet"),
                    ("retraite", "Retraité / Présent journée"),
                ],
                help_text="Profil d'occupation du logement",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="projection_10ans",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Projection consommation et coûts sur 10 ans",
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="recommandations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des recommandations d'optimisation",
            ),
        ),
        migrations.CreateModel(
            name="AppareilConsommation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("refrigeration", "Réfrigération"),
                            ("lavage", "Lavage"),
                            ("cuisson", "Cuisson"),
                            ("audiovisuel", "Audiovisuel"),
                            ("eclairage", "Éclairage"),
                            ("piscine", "Piscine"),
                            ("spa", "Spa/Jacuzzi"),
                            ("vehicule", "Véhicule électrique"),
                            ("autre", "Autre"),
                        ],
                        help_text="Catégorie de l'appareil",
                        max_length=30,
                    ),
                ),
                (
                    "type_appareil",
                    models.CharField(
                        help_text="Type précis (ex: frigo_combine, lave_linge, tv_55)",
                        max_length=50,
                    ),
                ),
                (
                    "nom_affichage",
                    models.CharField(
                        blank=True,
                        help_text="Nom pour affichage utilisateur (ex: 'Réfrigérateur combiné A+++')",
                        max_length=100,
                    ),
                ),
                (
                    "nombre",
                    models.IntegerField(
                        default=1, help_text="Nombre d'appareils identiques"
                    ),
                ),
                (
                    "classe_energetique",
                    models.CharField(
                        blank=True,
                        help_text="Classe énergie (A+++, A++, A+, A, B, C)",
                        max_length=10,
                    ),
                ),
                (
                    "puissance_w",
                    models.IntegerField(
                        blank=True, help_text="Puissance en Watts", null=True
                    ),
                ),
                (
                    "cycles_semaine",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de cycles par semaine (lave-linge, lave-vaisselle, sèche-linge)",
                        null=True,
                    ),
                ),
                (
                    "heures_jour",
                    models.FloatField(
                        blank=True,
                        help_text="Heures d'utilisation par jour (TV, ordinateur, pompe piscine)",
                        null=True,
                    ),
                ),
                (
                    "mois_debut",
                    models.IntegerField(
                        blank=True,
                        help_text="Mois de début d'utilisation (1-12) pour équipements saisonniers",
                        null=True,
                    ),
                ),
                (
                    "mois_fin",
                    models.IntegerField(
                        blank=True,
                        help_text="Mois de fin d'utilisation (1-12)",
                        null=True,
                    ),
                ),
                (
                    "km_an",
                    models.IntegerField(
                        blank=True,
                        help_text="Kilomètres par an (véhicule électrique)",
                        null=True,
                    ),
                ),
                (
                    "conso_100km",
                    models.FloatField(
                        blank=True,
                        help_text="Consommation kWh/100km (véhicule électrique)",
                        null=True,
                    ),
                ),
                (
                    "rendement_charge",
                    models.FloatField(
                        blank=True,
                        help_text="Rendement de charge 0-1 (véhicule électrique)",
                        null=True,
                    ),
                ),
                (
                    "pct_recharge_domicile",
                    models.IntegerField(
                        blank=True,
                        help_text="% de recharge à domicile (véhicule électrique)",
                        null=True,
                    ),
                ),
                (
                    "consommation_annuelle",
                    models.FloatField(help_text="Consommation annuelle en kWh"),
                ),
                (
                    "consommation_mensuelle",
                    models.JSONField(
                        default=list,
                        help_text="Liste de 12 valeurs (consommation mensuelle en kWh)",
                    ),
                ),
                (
                    "cout_annuel",
                    models.FloatField(
                        blank=True, help_text="Coût annuel estimé en €", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consommation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appareils",
                        to="frontend.consommationcalculee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil consommation (mode expert)",
                "verbose_name_plural": "Appareils consommation (mode expert)",
                "ordering": ["categorie", "type_appareil"],
            },
        ),
    ]
