# Generated by Django 4.2.18 on 2026-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_consommationcalculee_economie_optimisation_hphc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consommationcalculee",
            name="puissance_compteur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3kVA", "3 kVA"),
                    ("6kVA", "6 kVA"),
                    ("9kVA", "9 kVA"),
                    ("12kVA", "12 kVA"),
                    ("15kVA", "15 kVA"),
                    ("18kVA", "18 kVA"),
                    ("24kVA", "24 kVA"),
                    ("30kVA", "30 kVA"),
                    ("36kVA", "36 kVA"),
                ],
                default="",
                help_text="Puissance souscrite du compteur",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="type_contrat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("hphc", "Heures Pleines / Heures Creuses"),
                    ("tempo", "Tempo"),
                ],
                default="base",
                help_text="Type de contrat électrique",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consommationcalculee",
            name="type_cuisson",
            field=models.CharField(
                blank=True,
                choices=[
                    ("induction", "Induction"),
                    ("vitroceramique", "Vitrocéramique"),
                    ("gaz", "Gaz"),
                    ("mixte", "Mixte"),
                ],
                default="",
                help_text="Type de plaque de cuisson",
                max_length=50,
            ),
        ),
    ]
