# Generated by Django 4.2.18 on 2026-01-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_ajout_champs_cuisson_contrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="consommation_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations_generees",
                to="frontend.consommationcalculee",
                verbose_name="Analyse de consommation source",
            ),
        ),
    ]
