# Generated by Django 4.2.18 on 2026-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_installation_consommation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="adresse",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
