# Generated by Django 4.2.18 on 2026-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_alter_installation_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultat",
            name="objectif_optimisation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rentabilite", "Rentabilité"),
                    ("autonomie", "Autonomie"),
                    ("equilibre", "Équilibre"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="puissance_recommandee_kwc",
            field=models.FloatField(
                blank=True, help_text="Puissance optimale recommandée", null=True
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="taux_autoproduction_pct",
            field=models.FloatField(
                default=0,
                help_text="Part de la consommation couverte par la production",
            ),
        ),
    ]
