# Generated by Django 4.2.18 on 2026-02-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0009_resultat_objectif_optimisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="appareils_json",
            field=models.TextField(
                blank=True,
                help_text="Stockage JSON des appareils programmables et leurs horaires",
                null=True,
                verbose_name="Configuration des appareils (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="consommation_annuelle",
            field=models.FloatField(
                blank=True,
                help_text="Consommation électrique annuelle du foyer",
                null=True,
                verbose_name="Consommation annuelle (kWh)",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="profile_type",
            field=models.CharField(
                blank=True,
                help_text="actif_absent, teletravail, retraite, famille",
                max_length=20,
                null=True,
                verbose_name="Type de profil d'occupation",
            ),
        ),
    ]
