# Generated by Django 4.2.18 on 2026-02-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_calc", "0007_alter_consumptionprofilemodel_dpe"),
        ("frontend", "0010_installation_appareils_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="consumption_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations",
                to="solar_calc.consumptionprofilemodel",
                verbose_name="Profil de consommation détaillé",
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="autoconsommation_kwh_actuel",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Autoconsommation scénario actuel (kWh)",
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="autoconsommation_kwh_optimise",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Autoconsommation scénario optimisé (kWh)",
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="autoconsommation_ratio_actuel",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Taux autoconsommation actuel (%)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="autoconsommation_ratio_optimise",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Taux autoconsommation optimisé (%)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="economie_annuelle_actuel",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Économie annuelle actuel (€)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="economie_annuelle_optimise",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Économie annuelle optimisé (€)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="gain_autoconso_kwh",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gain autoconsommation (kWh)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="gain_autoconso_pct",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gain autoconsommation (%)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="gain_economie_25ans",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gain économique sur 25 ans (€)"
            ),
        ),
        migrations.AddField(
            model_name="resultat",
            name="gain_economie_annuel",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gain économique annuel (€)"
            ),
        ),
    ]
