# Generated by Django 4.2.18 on 2026-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_installation_consumption_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="orientation",
            field=models.CharField(
                choices=[
                    ("N", "Nord"),
                    ("NE", "Nord-Est"),
                    ("E", "Est"),
                    ("SE", "Sud-Est"),
                    ("S", "Sud"),
                    ("SW", "Sud-Ouest"),
                    ("W", "Ouest"),
                    ("EW", "Est/Ouest (réparti)"),
                    ("NW", "Nord-Ouest"),
                ],
                max_length=2,
            ),
        ),
    ]
