# Generated by Django 4.2.18 on 2026-02-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0012_alter_installation_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="facteur_ombrage",
            field=models.IntegerField(
                choices=[
                    (0, "Aucun (dégagé)"),
                    (10, "Léger (cheminée, antenne)"),
                    (20, "Modéré (arbre ou bâtiment proche)"),
                    (30, "Important (grands arbres, immeuble)"),
                ],
                default=0,
                help_text="Pourcentage de pertes dues à l'ombrage (0-30%)",
                verbose_name="Facteur d'ombrage (%)",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="type_onduleur",
            field=models.CharField(
                choices=[
                    ("string", "Onduleur central (string)"),
                    ("micro", "Micro-onduleurs"),
                    ("optimiseurs", "Onduleur + optimiseurs"),
                ],
                default="string",
                help_text="Type de solution onduleur",
                max_length=20,
                verbose_name="Type d'onduleur",
            ),
        ),
        migrations.AlterField(
            model_name="installation",
            name="orientation",
            field=models.CharField(
                choices=[
                    ("N", "Nord"),
                    ("NE", "Nord-Est"),
                    ("E", "Est"),
                    ("SE", "Sud-Est"),
                    ("S", "Sud"),
                    ("SW", "Sud-Ouest"),
                    ("W", "Ouest"),
                    ("NW", "Nord-Ouest"),
                ],
                max_length=2,
            ),
        ),
    ]
