# Generated by Django 4.2.18 on 2026-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0013_installation_facteur_ombrage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultat",
            name="objectif_optimisation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rentabilite", "Rentabilité"),
                    ("autonomie", "Autonomie"),
                    ("equilibre", "Équilibre"),
                    ("revente", "Vente totale"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
