# Generated by Django 4.2.18 on 2026-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0014_alter_resultat_objectif_optimisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultat",
            name="objectif_optimisation",
        ),
        migrations.AddField(
            model_name="resultat",
            name="objectif",
            field=models.CharField(
                choices=[
                    ("rentabilite", "Rentabilité"),
                    ("autonomie", "Autonomie"),
                    ("equilibre", "Équilibre"),
                    ("revente", "Vente totale"),
                ],
                default="equilibre",
                max_length=20,
                verbose_name="Objectif d'optimisation",
            ),
        ),
    ]
