# Generated by Django 4.2.18 on 2026-02-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0015_remove_resultat_objectif_optimisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="cout_installation_personnalise",
            field=models.FloatField(
                blank=True,
                help_text="Si renseigné par l'utilisateur (devis), utilisé à la place de l'estimation.",
                null=True,
                verbose_name="Coût installation personnalisé (€)",
            ),
        ),
    ]
