# Generated by Django 4.2.18 on 2026-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0016_installation_cout_installation_personnalise"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="surface_toiture_m2",
            field=models.FloatField(
                blank=True,
                help_text="Surface disponible pour les panneaux. 1 kWc ≈ 6.5 m²",
                null=True,
                verbose_name="Surface toiture disponible (m²)",
            ),
        ),
    ]
