# Generated by Django 4.2.18 on 2026-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0017_installation_surface_toiture_m2"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="objectif",
            field=models.CharField(
                choices=[
                    ("rentabilite", "Rentabilité"),
                    ("autonomie", "Autonomie"),
                    ("equilibre", "Équilibre"),
                    ("revente", "Vente totale"),
                ],
                default="rentabilite",
                max_length=20,
                verbose_name="Objectif d'optimisation",
            ),
        ),
    ]
