# Generated by Django 4.2.18 on 2026-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0018_installation_objectif"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="type_installation",
            field=models.CharField(
                choices=[
                    ("toiture", "En toiture"),
                    ("sol", "Au sol"),
                    ("ombriere", "Ombrière"),
                ],
                default="toiture",
                max_length=20,
                verbose_name="Type d'installation",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="type_panneau",
            field=models.CharField(
                choices=[
                    ("monocristallin_standard", "Monocristallin Standard (~20-21%)"),
                    ("topcon_hjt", "TOPCon / HJT (~22-24%)"),
                    ("bifacial", "Bifacial (~21-23%)"),
                ],
                default="monocristallin_standard",
                max_length=30,
                verbose_name="Type de panneaux",
            ),
        ),
    ]
