# Generated by Django 4.2.18 on 2026-02-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0020_resultat_puissance_hors_surface"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultat",
            name="puissance_hors_surface",
        ),
        migrations.AddField(
            model_name="installation",
            name="puissance_hors_surface",
            field=models.BooleanField(
                default=False,
                help_text="True si l'utilisateur a forcé une puissance dépassant la surface disponible",
                verbose_name="Puissance hors surface disponible",
            ),
        ),
    ]
