# Generated by Django 4.2.18 on 2026-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0021_remove_resultat_puissance_hors_surface_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="puissance_personnalisee",
            field=models.BooleanField(
                default=False,
                help_text="True si l'utilisateur a modifié manuellement la puissance recommandée",
                verbose_name="Puissance personnalisée par l'utilisateur",
            ),
        ),
    ]
