# Generated by Django 6.0.1 on 2026-01-09 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du profil')),
                ('annee_construction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2030)], verbose_name='Année de construction')),
                ('surface_habitable', models.FloatField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Surface habitable (m²)')),
                ('nb_personnes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de personnes')),
                ('dpe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='C', max_length=1, verbose_name='DPE')),
                ('type_chauffage', models.CharField(choices=[('non_electrique', 'Non électrique'), ('electrique', 'Électrique'), ('pompe_a_chaleur', 'Pompe à chaleur')], default='non_electrique', max_length=50, verbose_name='Type de chauffage')),
                ('type_ecs', models.CharField(choices=[('non_electrique', 'Non électrique'), ('electrique', 'Électrique'), ('thermodynamique', 'Thermodynamique')], default='non_electrique', max_length=50, verbose_name='Type ECS')),
                ('appareils_json', models.TextField(blank=True, null=True, verbose_name='Configuration des appareils (JSON)')),
                ('consommation_annuelle_kwh', models.FloatField(blank=True, null=True, verbose_name='Consommation annuelle (kWh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil de Consommation',
                'verbose_name_plural': 'Profils de Consommation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarInstallationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'installation")),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('altitude', models.FloatField(default=0, verbose_name='Altitude (m)')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('nombre_panneaux', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de panneaux')),
                ('puissance_panneau_wc', models.FloatField(default=500, verbose_name='Puissance par panneau (Wc)')),
                ('orientation_azimut', models.FloatField(default=180, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Orientation (azimut en degrés)')),
                ('inclinaison_degres', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Inclinaison (degrés)')),
                ('facteur_ombrage', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name="Facteur d'ombrage (0-1)")),
                ('type_onduleur', models.CharField(choices=[('central', 'Onduleur central'), ('micro_onduleur', 'Micro-onduleurs'), ('optimiseurs', 'Onduleur + optimiseurs')], default='central', max_length=50, verbose_name="Type d'onduleur")),
                ('puissance_onduleur_kw', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Puissance onduleur (kW)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Installation Solaire',
                'verbose_name_plural': 'Installations Solaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_annuelle_kwh', models.FloatField(verbose_name='Production annuelle (kWh)')),
                ('production_specifique_kwh_kwc', models.FloatField(verbose_name='Production spécifique (kWh/kWc/an)')),
                ('consommation_annuelle_kwh', models.FloatField(verbose_name='Consommation annuelle (kWh)')),
                ('autoconsommation_kwh', models.FloatField(verbose_name='Autoconsommation (kWh)')),
                ('injection_reseau_kwh', models.FloatField(verbose_name='Injection réseau (kWh)')),
                ('achat_reseau_kwh', models.FloatField(verbose_name='Achat réseau (kWh)')),
                ('taux_autoconsommation_pct', models.FloatField(verbose_name="Taux d'autoconsommation (%)")),
                ('taux_autoproduction_pct', models.FloatField(verbose_name="Taux d'autoproduction (%)")),
                ('donnees_horaires_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL des données horaires')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profil_consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='solar_calc.consumptionprofilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='solar_calc.solarinstallationmodel')),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
