# Generated by Django 4.2.18 on 2026-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_calc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionprofilemodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simulationmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="solarinstallationmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
