# Generated by Django 4.2.18 on 2026-01-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("solar_calc", "0002_alter_consumptionprofilemodel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarinstallationmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solar_installations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
