# Generated by Django 4.2.18 on 2026-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_calc", "0004_alter_consumptionprofilemodel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptionprofilemodel",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("actif_absent", "Actif absent en journée (travail externe)"),
                    ("teletravail", "Télétravail / Présence en journée"),
                    ("retraite", "Retraité (présent toute la journée)"),
                    ("famille", "Famille avec enfants"),
                ],
                default="actif_absent",
                help_text="Définit le pattern de consommation selon le mode de vie",
                max_length=20,
                verbose_name="Type de profil d'occupation",
            ),
        ),
    ]
