# Generated by Django 4.2.18 on 2026-02-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_calc", "0005_consumptionprofilemodel_profile_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumptionprofilemodel",
            name="annee_construction",
        ),
        migrations.AddField(
            model_name="consumptionprofilemodel",
            name="periode_construction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non renseignée"),
                    ("avant_1975", "Avant 1975"),
                    ("1975_2000", "1975-2000"),
                    ("2000_2012", "2000-2012"),
                    ("2013_2020", "2013-2020"),
                    ("apres_2021", "Après 2021"),
                ],
                max_length=20,
                null=True,
                verbose_name="Période de construction",
            ),
        ),
        migrations.AlterField(
            model_name="consumptionprofilemodel",
            name="dpe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
                null=True,
                verbose_name="DPE (Diagnostic de Performance Énergétique)",
            ),
        ),
    ]
