# Generated by Django 4.2.18 on 2026-02-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_calc",
            "0006_remove_consumptionprofilemodel_annee_construction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionprofilemodel",
            name="dpe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Je ne connais pas mon DPE"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
                null=True,
                verbose_name="DPE (Diagnostic de Performance Énergétique)",
            ),
        ),
    ]
