# Generated by Django 6.0.1 on 2026-01-10 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Clé de cache')),
                ('data', models.TextField(verbose_name='Données JSON')),
                ('api_source', models.CharField(choices=[('pvgis', 'PVGIS'), ('openweather', 'OpenWeatherMap'), ('solcast', 'Solcast')], max_length=50, verbose_name='Source API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('hit_count', models.IntegerField(default=0, verbose_name="Nombre d'accès")),
            ],
            options={
                'verbose_name': 'Cache API',
                'verbose_name_plural': 'Caches API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('altitude', models.FloatField(default=0, verbose_name='Altitude (m)')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='PVGISData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(default='PVGIS-SARAH2', max_length=50, verbose_name='Base de données PVGIS')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Année min')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='Année max')),
                ('raw_data', models.TextField(verbose_name='Données JSON brutes')),
                ('irradiation_annuelle_kwh_m2', models.FloatField(blank=True, null=True, verbose_name='Irradiation annuelle (kWh/m²)')),
                ('temperature_moyenne_annuelle', models.FloatField(blank=True, null=True, verbose_name='Température moyenne (°C)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Cache valide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration du cache")),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvgis_data', to='weather.location')),
            ],
            options={
                'verbose_name': 'Données PVGIS',
                'verbose_name_plural': 'Données PVGIS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Date et heure')),
                ('source', models.CharField(choices=[('pvgis', 'PVGIS'), ('openweather', 'OpenWeatherMap'), ('solcast', 'Solcast'), ('manual', 'Manuel')], default='pvgis', max_length=50, verbose_name='Source')),
                ('ghi', models.FloatField(blank=True, null=True, verbose_name='GHI - Global Horizontal Irradiance (W/m²)')),
                ('dni', models.FloatField(blank=True, null=True, verbose_name='DNI - Direct Normal Irradiance (W/m²)')),
                ('dhi', models.FloatField(blank=True, null=True, verbose_name='DHI - Diffuse Horizontal Irradiance (W/m²)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('vitesse_vent', models.FloatField(blank=True, null=True, verbose_name='Vitesse du vent (m/s)')),
                ('humidite', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humidité (%)')),
                ('pression', models.FloatField(blank=True, null=True, verbose_name='Pression (hPa)')),
                ('couverture_nuageuse', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Couverture nuageuse (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather.location')),
            ],
            options={
                'verbose_name': 'Donnée Météo',
                'verbose_name_plural': 'Données Météo',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['location', 'timestamp'], name='weather_wea_locatio_441a86_idx'), models.Index(fields=['timestamp'], name='weather_wea_timesta_7bce59_idx')],
                'unique_together': {('location', 'timestamp', 'source')},
            },
        ),
    ]
